### ISSUE TITLE
Question: Serialization

### ISSUE THREAD

**Issue by tcf909** [laverdet/isolated-vm#100]
I'm curious as to the overhead and latency incurred when serializing / deserializing in to an isolate?

I'm currently dealing with multiple processes in a way that you deal with isolates and found I needed to write my own serializer (beyond json.stringify + buffer) to have any chance of keeping latencies low. Given you are doing this all in a process between threads I figure you have a ton more opportunity around performance / latency -- just curious what your experience is passing data around the isolates.

Thanks!

**Comment by laverdet** [comment]
Serialization is all implemented in [external_copy.cc](https://github.com/laverdet/isolated-vm/blob/master/src/external_copy.cc). Strings and ArrayBuffers are copied out as raw bytes. ArrayBuffers can also be "transferred out" in which case you transfer ownership from one isolate to another and no copying takes place. Objects are serialized using v8's ValueSerializer API which is an implementation of the HTML5 structured clone algorithm, and uses v8's internal binary format to store the data. SharedArrayBuffers can referenced from more than one isolate at a time so no copying ever needs to happen.

So in some cases [ArrayBuffer, SharedArrayBuffer] no serialization even happens. In other cases [Strings, Objects] the serialization is implemented in C++ which is faster than any general purpose JS algorithm can ever hope to achieve. Furthermore since all the data lives in the same process you don't have to deal with inter-process communication.

I encourage you to benchmark the kinds of data transfers your application needs.. without a doubt isolated-vm will be faster than a multi-process pure-JS solution.
