### ISSUE TITLE
Using common class between isolates

### ISSUE THREAD

**Issue by Jerska** [laverdet/isolated-vm#101]
Hi @laverdet , thanks so much for this super useful library.
I've been playing with it quite a lot recently, and I'm currently hitting a wall for which I would love to get pointers.

I'm trying to use `URL` from within an isolate (and if possible, even make them transferable).
I understand this is not part of `v8` itself (and was actually super surprised to see that `JSON.parse/stringify` were).

Ideally, I'd like to be able to run:

```js
const ivm = require('isolated-vm');

const isolate = new ivm.Isolate({ memoryLimit: 128 });
const context = isolate.createContextSync();
const jail = context.global;

jail.setSync('global', jail.derefInto());
jail.setSync('ivm', ivm);

const script = isolate.compileScriptSync(
  `${function run() {
    const res = new URL('http://www.example.com');
    return new ivm.ExternalCopy(res).copyInto();
  }}`
);

script.runSync(context);
const url = context.global.getSync('run').applySync();

console.log('Found URL = ', url.href);
```

While I can easily provide a reference to a function, and classes are really just functions with prototypes, I'm still really confused as to how to do the same with classes (if possible).

**Comment by laverdet** [comment]
I recommend using webpack to build an environment with the added modules that you want. It can bundle up `url` for you into a single JS blob that you can execute in the isolate. You'd then be able to use URL in the isolate. The result would be transferable but wouldn't maintain the URL prototype methods. If you wanted to get those back you can probably do `result.__proto__ = URL.prototype`.

nodejs's url module is non-standard javascript so that's why it doesn't show up in the fresh isolate. JSON.parse, etc are a part of ECMAScript 5.1 released in 2011.

**Comment by Jerska** [comment]
Thanks for your answer.

What you suggested is indeed the solution I've been trying out since opening this issue and it works great.
We've been able to use https://github.com/jsdom/whatwg-url and bundle it in the webpack-compiled code.
To make those transferable, I resorted to a custom JSON `reviver` and `replacer` instead, allowing those to be nested and still easily transferable.

> JSON.parse, etc are a part of ECMAScript 5.1 released in 2011.
Thanks for clarifying that!
