### ISSUE TITLE
Timeout Ambiguity

### ISSUE THREAD

**Issue by kpdemetriou** [laverdet/isolated-vm#108]
First of all, awesome project, this is one of the best implementations of JS sandboxing I've seen.

Does the `timeout` option refer to CPU time or wall time? Whichever it is, how would one go about limiting the other (e.g. if `timeout` refers to wall time, how can I place a potentially more restrictive limit on CPU time)?

**Comment by laverdet** [comment]
Thanks for the complements.

`timeout` here refers to wall time, which matches the implementation in the built-in `vm` module. Perhaps that could be called out specifically since this project does expose more timers than `vm`.

I'm hesitant to add a second timeout for several reasons.. The timer and timeout code right now is pretty complex and adding more complexity seems unwise especially considering the current implementation is good enough for most applications. For the rare application that wants a wall and cpu timeout, you can do something like this by checking `cpuTime` in a "parent" isolate and disposing the executing isolate if it runs too long. There also doesn't seem to be a good cross-platform way to pull this off. Surprisingly, I was able to build a quick proof of concept in Linux with `pthread_getcpuclockid` and `clock_nanosleep` to wait on a CPU timer from another thread. Other platforms would need to use some kind of hybrid polling approach which would come with a lot of issues of its own. Also hyperthreading makes CPU timers very inaccurate/inconsistent regardless.

**Comment by kpdemetriou** [comment]
Makes sense, thank you very much.
