### ISSUE TITLE
Question: is there a way to listen to when isolate disposes and the reason for it

### ISSUE THREAD

**Issue by ErkoKnoll** [laverdet/isolated-vm#113]
Hi,

I'm simulating a malicious user and trying to crash the isolate which I can do by leaking memory. Malicious script is following:
```
const buffer: number[] = [];
const repeat = () => {
    setTimeout(() => {
        for (let i = 0; i < 999999; i++) {
            buffer.push(999999999999);
        }
        repeat();
    }, 10);
}
repeat();
```

At certain point when I'm doing reference callback (apply) I'm getting back 'Error: Isolate is disposed'. Obviously the Isolate has crashed because it ran out of memory, but I'm not getting back the exact error. It looks like the isolate has disposed itself silently. It would be useful if the isolate had an optional callback which will be called whenever the isolate gets disposed with the exact reason, so I would know exactly when it ran out of memory or something else happened.

Sometime it does report back a proper error, but it depends on timing: Error: Isolate was disposed during execution due to memory limit at

**Comment by laverdet** [comment]
I think you're running into the condition I discussed here: https://github.com/laverdet/isolated-vm/issues/109#issuecomment-492728991

If you run user code in response to a promise returning then there is no where to throw the error.

Callbacks on an isolate are tricky because callbacks aren't transferrable but isolates are.
