### ISSUE TITLE
Simple inter-context messaging?

### ISSUE THREAD

**Issue by beriberikix** [laverdet/isolated-vm#123]
My goal is to have a single Isolate spawn multiple contexts, each their own Wasm module, and define a "inter-context messaging" implementation for an experimental pub/sub sort of thing. I was roughly thinking that a context could store an array of "output context" and loop over each one when they have a message to send and have an `onMessage` handler. A message would be a single object.

I only just started with `isolated-vm` but I believe this should be possible looking at the samples in `/test`, like `cross-context-instance.js`. My hacky code got ugly pretty quickly so I was wondering if you had any pointers that might steer me in the right direction.

Cheers!

**Comment by laverdet** [comment]
Yeah this is definitely possible. This shouldn't be any harder than writing a pub/sub API in a single context without isolated-vm. I would recommend running `JSON.parse(JSON.stringify(...))` on any "messages" passed because otherwise instances of arrays and objects will be using the prototype from the originating context which can cause unexpected behavior or security vulnerabilities if your contexts don't trust each other.

If you have any questions specific to isolated-vm I'd be happy to answer them.
