### ISSUE TITLE
WebAssembly 

### ISSUE THREAD

**Issue by idleman** [laverdet/isolated-vm#131]
I got two questions about the WebAssembly and would be glad if someone can answer them:

1. Would it be safe to assume any unknown WebAssembly code can safely be executed in isolated-vm with the exception it can at most crash the process (and in that case would it be a v8 bug)? Even if the wasm-code was compiled for example with "threads", would never v8 native spawn any threads right? The runtime most implement it, right?

```
const module = new WebAssembly.Module(wasm, {});
  const instance = new WebAssembly.Instance(module, {
    env: {
      // If we don´t implement the proper methods here, would
      // the wasm module never be able to allocate any system threads - right?
    }
  });
```

2. How hard would it be to constructing a WebAssembly module natively from an underlying file, to speed up instantiation, like browsers do.

`const module = await isolate.compileWebAssembly('add.wasm');`

If there are just small changes would it be OK if I try to implement it the coming week or so?

**Comment by laverdet** [comment]
1. Yes WebAssembly is very stable. The spec hasn't changed at all (as far as I know) since the MVP in 2017 so the implementation has had time to mature. I've personally used WebAssembly in isolated-vm a lot and have never crashed it. Well I did crash it once but that was a bug in isolated-vm that was fixed quickly.
Regarding threads they are built on WebWorkers so if the isolate doesn't have access to WebWorkers (they don't) then WebAssembly won't be able to spin up new threads.

2. You can already load a .wasm from disk using the `WebAssembly.compile()` function.. in fact that's the only way to load wasm in general. You could speed this up by implementing the appropriate wasm hooks in ValueSerializer::Delegate and ValueDeserializer::Delegate. You would need to use `GetTransferrableModule()` for this. This would make compiled wasm modules compatible with ExternalCopy so you could call `compiled = new ivm.ExternalCopy(WebAssembly.compile(...))` once and then you'd be able to load the compiled ASM code directly into as many isolates/contexts as you like.

You're welcome to give it a shot, I don't think this task is nearly as complicated as the dynamic import() issue.

**Comment by idleman** [comment]
Thank you for your prompt reply.

About using WebAssembly.compile and compile it in the main thread and then transfer it to the isolate would not be worth it for me. It will more or less take the same initialization time by just transfer the underlying typed array and compile it in the other isolate anyway. 

My original thought was if it would be a large performance gain to implement something as WebAssembly.instantiateStreaming (with the same API naming as isolated-vm). But after some extra thinking - probably not worth it. The local filesystem is a faster than a average network request, so the performance gain would be much less compared to a browser.

**Comment by laverdet** [comment]
You can use `v8.serialize` and `v8.deserialize` to save compiled wasm -> native machine code to disk. I believe that will skip the compilation stage but you would want to verify. Then you could load the serialized copy from disk and transfer it into as many isolates as you need.

**Comment by idleman** [comment]
Holy shit, it works. Never thought it would. Thanks laverdet!

Will close the thread because v8.serialize/v8.deserialize seems to be everything I need.

**Comment by laverdet** [comment]
You can still eke out some extra speed by implementing the wasm hooks in the serialization delegates. By using the default serialization it'll need to copy the whole chunk of memory which takes time and also uses more memory. I'll leave this open because the implementation should be dead simple so maybe I'll get to it.
