### ISSUE TITLE
Obtaining setTimeout functionality inside an isolate

### ISSUE THREAD

**Issue by perryiam** [laverdet/isolated-vm#136]
Using the example code with some modification, it seems like the default context does not include `setTimeout`.  Is this actually true?  If so, how can I get the functionality into the context.   I would prefer not to delegate back out but have the isolate and its own context have its own setTimeout and dispatch queue.

**Comment by laverdet** [comment]
That's correct, `setTimeout` is defined in the HTML standard *not* the JavaScript standard. Is there a reason you don't want to delegate out to nodejs?

**Comment by timperlabs** [comment]
Thanks for the quick response!

Maybe I don't understand what the implications of delegation.  Let me define what I think delegation means in case I have it wrong.  To delegate out, I would give the isolate a setTimeout that would pass out of the isolate a reference to the user callback(and other params) and then run the real setTimeout outside the isolate which then runs a function then enters the isolate to run the user function by unboxing the Reference.  Here are some concerns:

1.  A minor reason.  I want to avoid the hassle since setTimeout seems like a safe function for the isolate to have since it's just controlling scheduling on its own thread and context.

2. A serious reason. It seems like this pattern would use up resources in the global dispatch queue and cause contention and slow down the main thread instead of having as much of the computation reside solely on the isolate's thread as possible.

**Comment by laverdet** [comment]
1) `setTimeout` isn't really "safe". For one it can escape the `timeout` parameter passed into `Script..run()`. In `isolated-vm` when you invoke any methods that pass control to an isolate you know that when the function returns that the isolate isn't going to execute anymore until you give it permission again. By letting the isolate schedule its own tasks you violate that feature. Also isolates can't actually schedule anything themselves, they depend on the main nodejs isolate.

2) It won't use a noticeable amount of resources.

Early while developing `isolated-vm` I discussed adding support for some libuv methods in #27 but I don't think it's a good idea for now. I would recommend building the feature now with a stub or delegate and if that proves problematic I can look at other solutions.
