### ISSUE TITLE
Calling with `applySyncPromise` without specifying options throws

### ISSUE THREAD

**Issue by nsamsonau-pal** [laverdet/isolated-vm#149]
Calling with `fun.applySyncPromise(undefined, [])` without specifying options throws `TypeError: `result` options are not available for `applySyncPromise` could not be cloned`. Although specifying `{}` removes the exception, it's impossible without specifying all options due to #148

**Comment by SpencerSharkey** [comment]
For this one, I'm not so sure the assertion here is required:
https://github.com/laverdet/isolated-vm/blob/bc28b77425cd48574ec8b30c1a4097cd34bbf67d/src/module/reference_handle.cc#L257-L259

if the assertion is removed, I believe we reach the behavior prior to 3.x where the resolved/returned values must be transferable. I'm not 100% sure on this, though.

**Comment by laverdet** [comment]
@SpencerSharkey the intent of this check is to ensure you haven't tried to set `{result:{...}}` options. The issue isn't the check it's that the default value is being set. `applySyncPromise` has its own promise handling logic that would conflict with the options supplied via `{result: {...}}` transfer options. I could make the two get along but it doesn't make a lot of sense. The point of the new transfer options feature is to make it so you don't have to pass the `isolated-vm` library into isolates. Since `applySyncPromise` can only invoke functions belonging to the default isolate you will always have access to your `ivm` object so you can just call `ExternalCopy` or whatever yourself. `applySyncPromise` is already a very messy function so I don't want to add any extra complications to it if I don't have to.

**Comment by laverdet** [comment]
9c980abe99e70dcac38da7aca34d015e88822643 should resolve this one

**Comment by SpencerSharkey** [comment]
that makes sense, thanks for the explanation. The new transfer options are great, I'm able to really clean up some code. Thanks for the hard work.
