### ISSUE TITLE
How to require module

### ISSUE THREAD

**Issue by wdh-1025** [laverdet/isolated-vm#152]
How to require module, such as "axios", thank you;

**Comment by laverdet** [comment]
You can't. Isolates created with this module are completely isolated from nodejs. You have to create a hook/delegate for any functionality you want to expose to an isolate.

**Comment by vkarpov15** [comment]
@laverdet do you have any docs on how to "create a hook/delegate for any functionality you want to expose to an isolate"?

**Comment by laverdet** [comment]
@vkarpov15 the `log` function under examples https://github.com/laverdet/isolated-vm#examples

**Comment by lokesh411** [comment]
Firstly, thanks for building this awesome library
`const ivm = require('isolated-vm');
const isolate = new ivm.Isolate

const context = isolate.createContextSync()

const jail = context.global;

// This make the global object available in the context as `global`. We use `derefInto()` here
// because otherwise `global` would actually be a Reference{} object in the new isolate.
jail.setSync("global", jail.derefInto());
//add logger
const logCallback = function (...args) {
  console.log('here inside log callback')
  console.log(...args);
};

const app = {
  log: logCallback
}

jail.setSync('app', app, { reference: true })

const code = `
  return new Promise((resolve, reject) => {
    app.log("something :: ", 5)
    return resolve(5)
  })
`
// const code = "return 2;"
context.evalClosure(code, [], { result: { promise: true, copy: true } }).then(val => console.log('val :: ', val)).catch(err => console.error('Error in running isolate :: ', err))
`
Hey @laverdet, I want to set an object to global context, but when I am calling the function inside the script, it's throwing me an error
`TypeError: app.log is not a function`
Can you suggest some workarounds for this?

**Comment by laverdet** [comment]
I think if you replace `jail.setSync('app', app, { reference: true })` with `jail.setSync('app', app)` it might work, as long as you're using version 4.x of isolated-vm. You need to be reasonable with your expectations of exporting objects into the isolate. Isolates in isolated-vm might as well be on a different computer over the internet. They're in different heaps managed by different isolates.

**Comment by lokesh411** [comment]
Got it @laverdet . I tried that, I am getting`TypeError: A non-transferable value was passed`. I am using version 4.2 of isolated-vm
