### ISSUE TITLE
How to proper log references

### ISSUE THREAD

**Issue by waldemarnt** [laverdet/isolated-vm#157]
I'm trying to do something similar to the example on the README where it creases a `log` function to be used similar to the `console.log` but the example only supports transferable that can be copied.
How would that work for references? I'm trying to log a function and a promise for example, as the code below
```javascript
const ivm = require('isolated-vm');
const isolate = new ivm.Isolate({ memoryLimit: 128 });

const context = isolate.createContextSync();
const jail = context.global;

jail.setSync('global', jail.derefInto());

const logCallback = function(...args) {
  console.log('test', ...args);
};
context.evalClosureSync(`global.log = function(...args) {
  $0.applySync(undefined, args, { arguments: { reference: true }});
}`, [ logCallback ], { arguments: { reference: true } });

context.evalSync('log(function(){})');
context.evalSync('log(Promise.resolve(true))');
```

When the arguments being passed are references they will be logged as `Reference {}` (which is expected), but if I try to deference it inside the `logCallback` function I'll get an error because the Reference doesn't belong to that isolate.
I can't run apply on the log reference because it would give back the value itself, I wanna log the function that is being referenced.

**Comment by laverdet** [comment]
It really depends on what's important to you. A console/tty is a plain stream of characters and converting arbitrary references in JavaScript to a stream of characters is a lossy and approximate exercise. In nodejs when you invoke `console.log` you get a really nice looking dump. That's because the nodejs team has written a 2,000 line long print routine for you (see nodejs: [lib/internal/util/inspect.js](https://github.com/nodejs/node/blob/4fefd181c759f3e8a7297bb3f9203d2c7841b14a/lib/internal/util/inspect.js)). On the other hand in Chrome's web inspector if you log a value you get a rich interactive inspector.

With that in mind here is the first step you might take:
```js
context.evalClosureSync(`global.log = function(...args) {
  $0.applySync(undefined, args.map(arg => String(arg)));
}`, [ logCallback ], { arguments: { reference: true } });
```

This will convert everything logged to a string before passing it back to the nodejs isolate. So now your logs would look like this:
```
test function(){}
test [object Promise]
```

On the other hand if you try and do `log({ key: "value" })` you're going to get back `[object Object]`. Maybe that's fine and maybe it isn't. It'll be up to you to build out the plumbing for logging what's important to you.

**Comment by waldemarnt** [comment]
@laverdet thanks for the quick reply! Yeah, you are right I guess implementing something similar to what nodejs does is a bit too much for my use case. I guess I can use string for the reference cases (functions, promises, etc) and for objects and arrays I can just pass them as a copy and they will be printed well.
