### ISSUE TITLE
Webpack and modules

### ISSUE THREAD

**Issue by taylorSando** [laverdet/isolated-vm#170]
How are you using webpack so that you can build a single javascript file that you can run with something like compileScriptSync?

All I get is a `require is not defined` when trying to actually runSync on the script/context.

**Comment by laverdet** [comment]
Probably what is happening is your package is trying to include `http` or `fs` or something. `isolated-vm` doesn't supply any of that stuff for you, so you will need to build a safe replacement for whatever it is that you need. Webpack inside `isolated-vm` can handle any pure javascript packages like lodash, react, moment, or redux because these don't do anything with the filesystem, network, or DOM. If you try to pull in something like express, axios, etc then it's not going to work because these are dependent on APIs that not plain javascript.

**Comment by ScriptedAlchemy** [comment]
Could these externals like fs or fetch be passed via shared memory or context. So while the isolate doesn’t have access to these, I could grant it access to some host resources. I’ve been using this tactic when using WASM isolates for quickjs via hostToC callback

**Comment by laverdet** [comment]
You can grant access to resources one callback at a time.
