### ISSUE TITLE
ExternalCopy BigInt support

### ISSUE THREAD

**Issue by Jerska** [laverdet/isolated-vm#172]
Hey @laverdet ! Thanks again for this awesome library. :)

We just started to try to inject `node`'s `process.hrtime.bigint()` into the isolate and realised, to our surprise, that bigint was not a supported type for `external_copy`.
Indeed, looking at the `CopyFromPrimitives` method, we could see that it's not in the list handled by `CopyIfPrimitive`.

Would there be any chance you could add support for it?

By the way, looking at the code, I saw only references to `int32` and `uint32`, and if you have some time, I'd love to ask you how this supports floating numbers. I thought numbers in JS used 64 bytes and floats were using the same underlying structure, explaining why `Number.MAX_SAFE_INTEGER` is not 2^63-1, so I would have understood if there was references to `uint64` & `int64`.

**Comment by laverdet** [comment]
Thanks for pointing this out. I just added support for bigints, I'll push a new npm version today or tomorrow.

Floats are represented with the `double` type which is a 64-bit float type. The JS spec doesn't actually say anything about 32 bit numbers, as far as JS is concerned everything is a `double`. Modern JS engines will use ints under the hood when it's safe because it's a lot faster. The highest double you can have without losing whole number accuracy is `2**53-1` which is a superset of int32_t. And actually if you want to keep your v8 code at top speed all your numbers should be within `-2**31` -> `2**31-1` which is considered an "small integer" or SMI.

**Comment by Jerska** [comment]
Again, thank you so much for the fast answer.
Thank you also for the detailed expanation on numbers, this is super clear and helpful. :)
