### ISSUE TITLE
createSnapshot OOMs the node process

### ISSUE THREAD

**Issue by nsamsonov** [laverdet/isolated-vm#188]
Basically, the title. I tried on node 10/12/14.  Based on the code, I would expect it to be ran inside an isolate, so very curious why it OOMs. 

Shortest repro
```typescript
require("isolated-vm").Isolate.createSnapshot([{ code: "l = []; for (let i = 0; i < 1e11; i++) l.push(i*i)" }])
```

May it be related to https://github.com/laverdet/isolated-vm/issues/107? 

Edit: edited snapshot code to avoid confusion with #107

**Comment by nsamsonov** [comment]
Just to be clear, using `code: "l = []; for (let i = 0; i < 1e11; i++) l.push(i*i)"` also crashes.

**Comment by laverdet** [comment]
This should be documented better but snapshot creation is not offered memory or isolation safety. If you are passing in user code I recommend wrapping ther code in a function body, snapshotting that, and then when starting the snapshot you call the function.

**Comment by nsamsonov** [comment]
Interesting. What exactly do you mean by isolation safety? It does seem like it runs in a different context without access to node functions and stuff, so I assume there is no shared memory.

If we wrap user code in a function body, are there still safety implications? 

To add some context, we use snapshots to cache user code bundles, which are quite significant in size. Creating the isolate takes around ~250ms for us, and snapshots allow us to avoid that latency during execution.

**Comment by laverdet** [comment]
There's no memory or execution limits, and it runs in the thread of the caller instead of a new thread. If you create a snapshot with `for(;;);` it'll lock up the process instead of just crashing it. You can't access anything dangerous like `fs` but as you learned it's easy to crash the process which can be troublesome. v8's snapshots are also super finicky and made pretty much only with the intent of defining a bunch of known functions. Someone else discovered in #151 if you do `new Intl.DateTimeFormat()` in a snapshot it'll also crash the process.

If you wrap the user's code in a function body there won't be any safety issues unless you pass a multi-gigabyte and it runs out of memory. Also you *must* make sure the code is valid on its own first otherwise the user could pass in something like `}crash();function a(){` which then if you wrapped it via ``const  wrapped = `function startup() { ${userCode} }`;`` it would of course escape the wrapped function. You can check this by ensuring `new Function(userCode)` doesn't throw.

I'd also recommend giving the `produceCachedData` and `cachedData` options on `compileScript` a try. Theoretically those can speed up compilation without any of the messiness of snapshots but I haven't tested the speed.
