### ISSUE TITLE
Catch async uncaught exceptions

### ISSUE THREAD

**Issue by rs** [laverdet/isolated-vm#2]
Would it be possible to catch async uncaught exception on a per context basis?

```js
const ivm = require('isolated-vm');
const isolate = new ivm.Isolate();
const context = isolate.createContextSync();
const jail = context.globalReference();

jail.setSync('asyncException', new ivm.Reference(() => {
    setTimeout(() => {throw new Error()}, 1000);
}));

const script = isolate.compileScriptSync('asyncException.apply()');

script.run(context).catch((e) => {
    // Won't catch async exception, would be nice to be able to wait for
    // all scheduled events and capture their exceptions if any.
});
```

**Comment by laverdet** [comment]
In this case the exception is actually thrown from the outer context (the default node environment) so it would be up to you to catch it, or not throw it in the first place. Once you're in `asyncException` you're now running in the node context therefore setTimeout will eventually throw and the behavior is the same as if you didn't have any isolated-vm magic.

And actually you may notice that `setTimeout` doesn't exist at all in isolated-vm contexts. v8 only gives you a barebones JS environment and since setTimeout needs an event loop or some other kind of timing mechanism that's left to the embedder to implement. In our case nodejs has implemented setTimeout so we can implement it just by wrapping node's setTimeout:

```js
let ivm = require('isolated-vm');
let isolate = new ivm.Isolate();
let context = isolate.createContextSync();
let jail = context.globalReference();

jail.setSync('ivm', ivm); // unsafe; be sure to take care of this reference with untrusted code
jail.setSync('setTimeout', new ivm.Reference(function(fn, timeout) {
  setTimeout(function() {
    try {
      fn.applySync();
    } catch (err) {
      console.log('inner context threw an error');
    } 
  }, timeout);
}));
// Since the `setTimeout` we set above is a weird ivm.Reference we use this wrapper
// to handle the apply and reference logic
isolate.compileScriptSync(`
setTimeout = function(setTimeout) {
  return function(fn, timeout) {
    setTimeout.applySync(null, [ new ivm.Reference(fn), timeout ]);
  };
}(setTimeout);
`).runSync(context);

const script = isolate.compileScriptSync('setTimeout(() => { throw new Error }, 100)');

script.runSync(context);
// logs: inner context threw an error
```

Although you are correct that uncaught errors from Promises will be lost. I should be able to detect this and throw the exception directly from the `run` or `apply` call.

**Comment by rs** [comment]
Yes, my example wasn't great. My point is to say, the executed code should never be able to leak exceptions to the main v8 context. The wrapping technique is great, but as you mentioned, it won't cover all cases.

**Comment by laverdet** [comment]
There is currently never a case where an exception leaks into the main context. runSync or applySync will throw if the jailed code throws but that's expected behavior. Exceptions in the jailed promises will be lost, but won't find their way into the main context.

**Comment by laverdet** [comment]
I just pushed a decent enough fix, but there still remains a small gap in coverage that I don't think is terribly important. A single script can actually throw multiple exceptions by using promises. Consider:

```js
let ivm = require('isolated-vm');
let isolate = new ivm.Isolate;
let context = isolate.createContextSync();
let script = isolate.compileScriptSync('throw new Error("error1"); Promise.resolve().then(() => { throw new Error("error2") })');
script.runSync(context);
```

In this case it will throw "error1" to the outer context and the "error2" message will be silently swallowed. Without a more sophisticated mechanism it's impossible to expose both exceptions. But in most applications the distinction isn't super important, you would just wrap runSync in a try-catch block and if it catches you send the error to the developer and dispose their isolate.
