### ISSUE TITLE
Wait for events

### ISSUE THREAD

**Issue by rs** [laverdet/isolated-vm#20]
Is there a way to get a promise that would resolve when all events scheduled by the context are done?

**Comment by laverdet** [comment]
Once `run` or `apply` return, the isolate is totally done until you give it some external events. The non-main isolates don't have an event loop of their own and depend on the main isolate to wake them up with external events.

**Comment by rs** [comment]
By main isolate you mean the main node’s one not managed by isolated-vm?

**Comment by laverdet** [comment]
Right the nodejs isolate is responsible for waking up isolates created by isolated-vm. Well, an isolated-isolated can wake up another isolated-isolate if it has a handle, but the main-nodejs-isolate would first have to wake one of them up.

**Comment by rs** [comment]
If the isolated code create promises, I have no way to know when they are all executed / resolved?

**Comment by laverdet** [comment]
v8 does provide a hook to notify the embedder of various promise life stage events, but I want to better understand the use case here. I understand that you want an isolate to finish its task before you dispose it or give it another task, but that should be inherent to `run` or `apply` finishing. A freshly created isolate has no way to schedule something which will eventually call a callback, therefore once `run` finishes you can assume that all promises it created have either already resolved or will never resolve without further interaction from you. If you expose some API to the isolate which asynchronously invokes a callback then that API would be under your control and you would know how many events are pending.

The only gap in coverage I can think of is if the inner isolate calls the async `apply` method on a reference it will receive a promise. Then once the function returns that promise will be resolved and the inner isolate will be woken up by that promise. In this case there would be no notification that the work is done. Additionally there is no way to timeout whatever code run in that promise's `then` handler.

**Comment by rs** [comment]
Thanks for the explanation. As you guessed, I had some exposed APIs that were not handled properly.

For my use-case, I create a single isolate per "app" with the app's code loaded using the snapshot feature. On those isolates, I create one context per request, and grab a global function from the context in order to use the `apply` method on it.

Is it better to create one isolate per request or this model is fine? What is the difference between the two models?

Also, it would be nice to describe how isolates/contexts interacts with node and how they are distributed on the thread pool in the README.

**Comment by laverdet** [comment]
I think the model you described is fine. A new isolate per request sounds like overkill. Each isolate you create has some overhead (in terms of CPU used to build the isolate and memory to keep it around), but what you get is independence from the other isolates. For instance, every context in a single isolate shares garbage collection. Therefore if one context is running poorly written code which has a reference leak somewhere it will slow down other contexts running in that same isolate. Garbage collection just runs whenever it feels like, so when a context loses the garbage collection lottery it has to pay for the garbage accumulated by all the other contexts. On the other hand, sharing resources is sometimes good. Since your contexts are all running the same function over and over they might be able to reuse some of the work from the last time the function ran, even if it was in a different context.

As for how isolated-vm interacts with the nodejs event loop it pretty much tries to stay out of it as much as possible. There's only one hook into the nodejs/libuv event loop which is used when the async functions need to send some data back to the default isolate. All non-default isolates run in their own thread pool when invoked with the async-style API. It's a pretty typical thread pool implementation which isn't super interesting. There's a small special case where isolates will prefer to run in a thread they've seen before because v8 tends to be faster in this case but it's not terribly complicated.

**Comment by rs** [comment]
Very interesting details. Thank you.

Just to make sure I understand it correctly: all isolate actual JS code are running in the same thread or you are able to balance the load between threads? Said another way, do we need to play with multiple node process to balance the load of different isolates on all cores?

**Comment by laverdet** [comment]
One process should be enough to utilize all CPU cores. You can confirm with the following:

```js
'use strict';
let ivm = require('isolated-vm');
for (let ii = 0; ii < require('os').cpus().length; ++ii) {
  (async function() {
    let isolate = new ivm.Isolate;
    await (await isolate.compileScript('for(;;);')).run(await isolate.createContext());
  })(); 
}
```

Activity Monitor on my laptop w/ 4 hyper-threaded cores shows ~780% CPU usage.

**Comment by rs** [comment]
So is it safe to say that each isolate will be scheduled on the libuv thread pool and that we won't end up with one new thread per isolate?

**Comment by laverdet** [comment]
isolated-vm has its own thread pool. The only time it pings the libuv event loop is for the default isolate because nodejs needs to always run in the same thread. isolated-vm isolates don't have that restriction, they can run in any thread.

Right now the thread pool has a hardcoded limit of 8 for some reason, but if an isolate needs to run and the thread pool is too busy it will just create its own temporary thread so there's never a case where an isolate will be blocked. Making new threads actually isn't too expensive on modern environments.. the most time consuming part is synchronizing data between threads and that needs to happen regardless of whether or not a thread pool is used. The main reason I have a thread pool in place at all is because v8 stores some data per isolate in thread-specific memory so if you reuse threads you can save some setup and destruction time when invoking the v8 vm.

My recommendation for maximum performance in your application is to use something like [async.queue](https://caolan.github.io/async/docs.html#queue) with `concurrency` of `os.cpus().length` or maybe `os.cpus().length + 1`. This will ensure you have work running on every core without letting too many threads through causing lock contention.
