### ISSUE TITLE
isolated-vm comparison details

### ISSUE THREAD

**Issue by tcf909** [laverdet/isolated-vm#229]
I noticed the main Readme says that the native node.js workers do not support inspector. I was hoping you can elaborate about that.

I'm evaluating isolated-vm for an upcoming project. I really loved your work with Fibers (even if it isn't feasible to use moving forward). I'm not that versed in the isolate options for Node.js, but noticed inspector support seems to work just fine using node.js + intellij if I set a breakpoint in a worker thread.

Hoping you can clarify / elaborate about your comparison assertion.

Thanks @laverdet !

**Comment by tcf909** [comment]
I also noticed the availability of worker.resourceLimits in the node.js worker module. 

```
Added in: v13.2.0, v12.16.0
<Object>
maxYoungGenerationSizeMb <number>
maxOldGenerationSizeMb <number>
codeRangeSizeMb <number>
stackSizeMb <number>
```

Does this compare to your memory limits as well I'm assuming?

**Comment by laverdet** [comment]
It looks like worker threads have gotten undocumented inspector support since I wrote that blurb. You still can't inspect in Chromium, though https://github.com/nodejs/node/issues/26609

`resourceLimits` are the v8 hard limits, and if you hit them in worker_threads the whole process will crash. isolated-vm takes precautions to avoid crashing the process in these cases.
