### ISSUE TITLE
why is isloated-vm secure?

### ISSUE THREAD

**Issue by tigercosmos** [laverdet/isolated-vm#246]
As the worker thread in NodeJS is also using an isolate (in C level), what are the "secure" parts of isolated-vm except enabling memory control? cc @laverdet

**Comment by y21** [comment]
In a worker thread you still have access to node.js, so it's not optimal for running untrusted code. One can use `require("fs")` to get access to the file system or `require("child_process")` to spawn processes/run arbitrary commands
Isolates created by isolated-vm do not have access to anything node.js specific unless you expose them to the isolate, so no access to the host by default

**Comment by tigercosmos** [comment]
@laverdet what's your point of view?

**Comment by laverdet** [comment]
I don't really have much to add. v8 is mostly secure and therefore isolated-vm is mostly secure. nodejs isn't secure because it adds insecure features.

**Comment by koto** [comment]
v8 isolates are not "mostly secure", especially for isolating arbitrary code. v8 itself lists the mitigations for [running untrusted code](https://v8.dev/docs/untrusted-code-mitigations#if-you-do-execute-untrusted-code%E2%80%A6) - one of them is turning on the Spectre mitigations, yes, but that needs to be used _alongside_ sandboxing in a separate process. 

You might be providing a false level of security by just saying that it's now secure to run untrusted code with this project.

**Comment by laverdet** [comment]
Thanks for pointing that out Krzysztof. My hope is that users of isolated-vm take the time to consider the weaknesses of v8 and isolated-vm and weigh them against their own unique threat profile. v8 leaves a lot of responsibilities to the "embedder" in order to secure their application, and isolated-vm in turn passes those responsibilities onto the user of the module. I agree that the documentation around these issues could be improved.

As you're well aware, executing untrusted code in any runtime is an extraordinarily difficult problem which requires discipline and ongoing monitoring and maintenance. I'm not a consultant and I feel that walking users through a comprehensive list of best practices is outside the scope of this project. In the README I do link to the v8 wiki page you supplied above.. but I personally feel that even Google's own documentation on the matter is hilariously insufficient.

I do stand by the belief that isolated-vm is a powerful tool when used responsibly, and fills a unique niche in the module ecosystem. Consider that before isolated-vm the best available tool was vm2 which uses Reflect and Proxy to obstruct access to capabilities already granted within the nodejs isolate. In this context isolated-vm is a strict improvement. For users unable or unwilling to embed v8 directly in C++ this is about as good as it can get.

**Comment by koto** [comment]
Thanks for your answer. It's all fair, but I think you'll agree that security of using the isolated-vm is nuanced, as it's the function of the workloads it processes and the overall threat model. My gripe is with generalized statements in the README like 'You might find this module useful if you need to run some untrusted code in a secure way'. It only as secure as Isolates themselves, which fail under e.g. memory corruption bugs, or Spectre. To me, untrusted code implies that the attacker might try to trigger such bugs (v8 exploits are often public), and that general description is thus misleading a bit. 

Similarly, the table at the bottom implies that isolated-vm lets you `safely run untrusted code`. I don't think that's true (or - it is, but only if your attacker doesn't try to exploit the runtime).

I really appreciate though that this is spelled out in the security section, thanks for that. Perhaps linking to this section from the description and the table would help make this limitation clear?

Anecdotally, I only learned about isolated-vm when someone I know was considering it for running completely untrusted code alongside their application, enticed by this description.

**Comment by laverdet** [comment]
I'll update the README with some more information on the subject and less promising language. I originally created isolated-vm for use in a JavaScript video game [Screeps](https://screeps.com/) [you should play it, it's fun], so advanced persistent threats with access to v8 0-days weren't a huge concern for us. Since the project has gained traction externally I agree it would be responsible to refresh the messaging here.

**Comment by laverdet** [comment]
22ed400de4cd65cbe537614af59228b3fc416f4b

**Comment by koto** [comment]
Thank you @laverdet, the update obviates all of my concerns, I really appreciate it. And now I'll be sure to check out Screeps :)
