### ISSUE TITLE
Passing a Reference through an ExternalCopy breaks the reference 

### ISSUE THREAD

**Issue by legraphista** [laverdet/isolated-vm#32]
Given an object like: 
```js
{ functionA: Reference { typeof: 'function' }, numberB: 1 }
```
 Passing set object through `ExternalCopy`'s `.copyInto()`/`.copy()` results in the following: 
```js
{ functionA: { typeof: 'function' }, numberB: 1 }
```

Not sure if this is the intended behaviour, but it looks like it tries to serialise the `Reference` as an object.  I'm trying to pass an object containing some functions from the main isolate to another isolate.

Is there a way in which it could keep the original, or `.copy()` it?

Sample code: 
```js
const ivm = require('isolated-vm');

const ref = new ivm.Reference(function aFunction() {});

const objectWithRef = { fn: ref, nr: 1 };

console.dir(ref);
console.dir(new ivm.ExternalCopy(ref).copy());
console.dir(objectWithRef);
console.dir(new ivm.ExternalCopy(objectWithRef).copy());
console.dir(new ivm.Reference(objectWithRef).deref()); // will not work in other isolates
```
output:
```
Reference { typeof: 'function' }
{ typeof: 'function' }
{ fn: Reference { typeof: 'function' }, nr: 1 }
{ fn: { typeof: 'function' }, nr: 1 }
{ fn: Reference { typeof: 'function' }, nr: 1 }
```

**Comment by laverdet** [comment]
Yeah this is expected behavior. `ExternalCopy` maintains no handles back into v8 so it's impossible to maintain references. When you pass an object it actually just does `JSON.stringify()` and stores the result of that in non-v8 memory.

If you need to pass many `Reference` instances to an isolate I recommend creating a function in the isolate to accept the references, and then invoke that function with `apply`.

**Comment by legraphista** [comment]
Thank you for the response! 
I eventually realised that that was the case, and worked around it.
