### ISSUE TITLE
Open Questions regarding Documentation

### ISSUE THREAD

**Issue by Nitwel** [laverdet/isolated-vm#388]
Hey there, we're using isolated-vm to run user-made extensions on our platform and still have some open questions regarding security and how stuff works in detail.

## Question 1
Starting with the following sentence:
> At a minimum you should take care not to leak any instances of isolated-vm objects (Reference, ExternalCopy, etc) to untrusted code. It is usually trivial for an attacker to use these instances as a springboard back into the nodejs isolate which will yield complete control over a process.

We would really like to understand why that is the case, as to us it is not trivial. It's no inconvenience for us to follow that guide, but it would be great to understand the reasons behind it.

## Question 2
Next, how Reference and ExternalCopy work under the hood. A reference is documented as follows:
> A instance of [Reference](https://github.com/laverdet/isolated-vm#class-reference-transferable) is a pointer to a value stored in any isolate.

It is likely meant that when passing to an isolate, it sends over a reference to the value created in Node.js, but the sentence sounds as if a Reference is a pointer to a value, and said value is stored in an isolate which doesn't make a lot of sense.

## Question 3
What's the difference between Reference and ExternalCopy? Both sound like memory gets allocated on the Node.js side, but what happens if you pass in an ExternalCopy directly into an isolate, will it create a Reference to an ExternalCopy or do something else?

## Question 4
Regarding TransferOptions, it is mentioned that without specifying those, functions do whatever they want, but it would be important for our understanding what function does exactly what when you don't pass in any TransferOptions.

Thanks again for this amazing library, it has opened a lot of new possibilities for us, but we really would love to get some more insight into understanding it more thoroughly. ❤️

**Comment by laverdet** [comment]
The main difference is the scheduler. Work which is scheduled from ivm to nodejs is done through libuv. Work which is scheduled from nodejs to ivm is done through a custom scheduler. Additionally, isolated-vm isolates can make use of *any* thread, including nodejs controlled threads. That's why you can invoke sync methods from nodejs, but not the other way around. When you invoke a sync method we aren't calling out to another thread, the allocated isolate just jumps into nodejs's thread, completes some work, and then leaves.

nodejs on the other hand allocates a thread per isolate, and that thread is dedicated to the given isolate. It's a perfectly fine system, and was just made for different purposes. There is some extra [CPU] overhead involved in sharing threads so for nodejs it probably makes sense since you shouldn't have a crazy number of threads. isolated-vm was made for a video game running code provided by 1000's of players so the memory overhead of each player was supposed to be as low as possible.

**Comment by Nitwel** [comment]
Thanks again for your answer. Will close this now as every question is resolved to us. 😄
