### ISSUE TITLE
Regular expressions don't work

### ISSUE THREAD

**Issue by tespindola** [laverdet/isolated-vm#389]
I'm trying to use regular expressions inside isolated, but it's not working correctly. Inside my script I have this:
```javascript
let value = "DEV PRICE20 - 20% Hipermas Agosto:hipermas-santander.png";
let matches = value.match(/DEV PRICE(\d+) - (.+):(.+)/)
```

But the matches variable is always null, so I investigated the problem is the "\\", I also tried to use global functions but I can't get the \ to be sent, I leave the example:
```javascript
await contextGlobal.global.set('test', (ex) => {
        let value = "DEV PRICE20 - 20% Hipermas Agosto:hipermas-santander.png";
        let reg = new RegExp(ex);
        return value.match(reg);
});

// script
let matches = test('DEV PRICE(\\d+) - (.+):(.+)') // null
```

Does anyone have any idea what I'm doing wrong? Because I did the tests outside the virtual machine and it works perfectly.

Any help is welcome, many thanks in advance.

**Comment by laverdet** [comment]
i can't help you if you don't post a complete program

**Comment by laverdet** [comment]
You didn't escape the \d:
```
-> % node
Welcome to Node.js v20.1.0.
Type ".help" for more information.
> `\d`
'd'
```

**Comment by tespindola** [comment]
And how can I escape it? Do you know any documentation where it indicates how to do the escapes?

**Comment by laverdet** [comment]
You can check out CodeAcademy for easy tutorials in JavaScript. You can also find a technical explanation of character escaping here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Character_escape

The problem is that the expression `"\d"` actually evaluates to the string "d". If you install a tool like eslint your IDE will warn you of a "useless escape": [eslint playground](https://eslint.org/play/#eyJ0ZXh0IjoiY29uc3QgYSA9IFwiXFxkXCI7Iiwib3B0aW9ucyI6eyJlbnYiOnt9LCJydWxlcyI6eyJjb25zdHJ1Y3Rvci1zdXBlciI6MiwiZm9yLWRpcmVjdGlvbiI6MiwiZ2V0dGVyLXJldHVybiI6Miwibm8tYXN5bmMtcHJvbWlzZS1leGVjdXRvciI6Miwibm8tY2FzZS1kZWNsYXJhdGlvbnMiOjIsIm5vLWNsYXNzLWFzc2lnbiI6Miwibm8tY29tcGFyZS1uZWctemVybyI6Miwibm8tY29uZC1hc3NpZ24iOjIsIm5vLWNvbnN0LWFzc2lnbiI6Miwibm8tY29uc3RhbnQtY29uZGl0aW9uIjoyLCJuby1jb250cm9sLXJlZ2V4IjoyLCJuby1kZWJ1Z2dlciI6Miwibm8tZGVsZXRlLXZhciI6Miwibm8tZHVwZS1hcmdzIjoyLCJuby1kdXBlLWNsYXNzLW1lbWJlcnMiOjIsIm5vLWR1cGUtZWxzZS1pZiI6Miwibm8tZHVwZS1rZXlzIjoyLCJuby1kdXBsaWNhdGUtY2FzZSI6Miwibm8tZW1wdHkiOjIsIm5vLWVtcHR5LWNoYXJhY3Rlci1jbGFzcyI6Miwibm8tZW1wdHktcGF0dGVybiI6Miwibm8tZXgtYXNzaWduIjoyLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOjIsIm5vLWV4dHJhLXNlbWkiOjIsIm5vLWZhbGx0aHJvdWdoIjoyLCJuby1mdW5jLWFzc2lnbiI6Miwibm8tZ2xvYmFsLWFzc2lnbiI6Miwibm8taW1wb3J0LWFzc2lnbiI6Miwibm8taW5uZXItZGVjbGFyYXRpb25zIjoyLCJuby1pbnZhbGlkLXJlZ2V4cCI6Miwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOjIsIm5vLW1pc2xlYWRpbmctY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1taXhlZC1zcGFjZXMtYW5kLXRhYnMiOjIsIm5vLW5ldy1zeW1ib2wiOjIsIm5vLW9iai1jYWxscyI6Miwibm8tb2N0YWwiOjIsIm5vLXByb3RvdHlwZS1idWlsdGlucyI6Miwibm8tcmVkZWNsYXJlIjoyLCJuby1yZWdleC1zcGFjZXMiOjIsIm5vLXNlbGYtYXNzaWduIjoyLCJuby1zZXR0ZXItcmV0dXJuIjoyLCJuby1zaGFkb3ctcmVzdHJpY3RlZC1uYW1lcyI6Miwibm8tc3BhcnNlLWFycmF5cyI6Miwibm8tdGhpcy1iZWZvcmUtc3VwZXIiOjIsIm5vLXVuZGVmIjoyLCJuby11bmV4cGVjdGVkLW11bHRpbGluZSI6Miwibm8tdW5yZWFjaGFibGUiOjIsIm5vLXVuc2FmZS1maW5hbGx5IjoyLCJuby11bnNhZmUtbmVnYXRpb24iOjIsIm5vLXVudXNlZC1sYWJlbHMiOjIsIm5vLXVudXNlZC12YXJzIjoyLCJuby11c2VsZXNzLWNhdGNoIjoyLCJuby11c2VsZXNzLWVzY2FwZSI6Miwibm8td2l0aCI6MiwicmVxdWlyZS15aWVsZCI6MiwidXNlLWlzbmFuIjoyLCJ2YWxpZC10eXBlb2YiOjJ9LCJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e30sImVjbWFWZXJzaW9uIjoxMiwic291cmNlVHlwZSI6InNjcmlwdCJ9fX0=)

This isn't specific to isolated-vm, you can observe this plainly in the nodejs repl example I posted above. Or another way:
```
> new RegExp(`DEV PRICE(\d+) - (.+):(.+)`)
/DEV PRICE(d+) - (.+):(.+)/
//         ^ look no slash
```
