### ISSUE TITLE
More states getters

### ISSUE THREAD

**Issue by jeromegn** [laverdet/isolated-vm#41]
The addition of `isDisposed` helps a lot. Is that also set while it is being disposed of?

It seems like surfacing a few more states would help predicting the lifecycle of isolates and contexts.

It'd be useful to be able to tell when an isolate is being disposed of, maybe `isDisposing`? I suspect there are other states to the isolate. Is creating an isolate really synchronous?

Contexts also have a few states. While they're being created, while they're being released and when they're actually released.

**Comment by laverdet** [comment]
`isDisposed` is set as soon as `isolate.dispose()` is called from any thread. So more accurately it should be called `isDisposedOrDisposing` but as far as nodejs is concerned the difference between the two isn't very important.

The status of "disposing" should only last for a couple hundred milliseconds at most. Also once an isolate is in the disposing state no more tasks can be scheduled, so all methods called from any thread will throw immediately. I could add this property but it would add some overhead to every isolate and some code complexity as well. Not a lot, but it's still some and I can't think of any time when this feature is useful. Consider the nodejs method `destroy()` on steams which is similar. After you call `destroy()` the resource (socket, file, whatever) is actually maybe still open for some short time, but it doesn't matter because it can no longer do anything.

Additionally, overuse of state flags like this can open you up to race conditions. Even with the `isDisposed` flag that exists now you could definitely have some errors with code that does `if (!isolate.isDisposed) { /* use the isolate */ }`. In between the flag check and use of the isolate it could have been disposed by another thread.

Isolate creation is indeed entirely synchronous. Once the constructor returns the isolate is ready and idle.

Contexts are more difficult to track because contexts can hold references to each other within the same isolate. It's up to v8's garbage collector to dispose of contexts (detecting dead circular references, etc). I could maintain a weak v8 reference to the context and allow you to see if the reference is still valid (i.e. hasn't been gc'd yet) but this could actually end up keeping the context alive for longer.

**Comment by jeromegn** [comment]
Fair enough. Thanks for clarifying.

I've opened this because we're trying to track down a condition where an isolate is disposed and it crashes the process entirely when something somewhere is trying to run code on it.

Of course it shouldn't be running that code in the first place. We have various checks to make sure the isolate is not disposed when we want to run code with it, but it still seems to happen sometimes. I think we have a race condition somewhere.

I agree that adding state a bit everywhere adds a lot of complexity and probably isn't desirable unless necessary.

I'll keep digging until I can fix that race condition.

**Comment by laverdet** [comment]
When you say crash the process entirely do you mean you get a scary v8 or c++ error, or is this a "graceful" js error thrown from somewhere that you weren't expecting?

**Comment by jeromegn** [comment]
We're catching unhandled errors and rejections, but still this one seems to get through the cracks somehow:

```
Error: Isolate is disposed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodeproxy@0.1.1 start:production: `ts-node --max_old_space_size=15360 ./src/index.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodeproxy@0.1.1 start:production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-14T23_07_55_444Z-debug.log
```

I'm going to try and find more thorough logs to see what happened before exactly.

**Comment by laverdet** [comment]
A stack trace would definitely be helpful there. I started working on trying to get some more information on that error but I'm a bit busy for the next several days so I won't have time to finish it. If you run the `extra-exceptions` branch I just pushed you can see the WIP which does manage to include a raw JSON stack trace on some of these errors.

**Comment by laverdet** [comment]
master should have useful stack traces now, give it a shot

**Comment by jeromegn** [comment]
That should be useful in the future!

We figured out the isolate was being disposed because of heap usage and we're not catching it as well in production.

The `text-encoding` package we're using in v8 seems to use a ton of memory. I'm measuring heap before and after decoding a 1.5MB ArrayBuffer and it adds around 60MB of heap to decode that text. We have a race condition between garbage collection and allocating a bunch of memory. Basically all of this memory is allocated to decode into a utf-8 string, and in parallel a promise is being fulfilled which is also using quite a bit of memory. We noticed that if we "await" that promise instead of just firing it, it gives enough time for v8 to garbage collect.

In "fly" terms, what's happening is a fetch + convert the body to a string + in parallel set an object in our persistent cache.

**Comment by jeromegn** [comment]
As a side note, if I try to profile memory allocation in an inspector, I don't get nearly those numbers. If I'm reading it right, I get at most 1.5-2MB x 2-3 allocated objects.

**Comment by laverdet** [comment]
The v8 inspector will probably only count objects that v8 allocated itself. Large ArrayBuffers will be externally allocated and don't count towards v8's heap. Note that isolated-vm keeps track of this memory separately and will terminate the isolate when the sum of externally allocated memory and v8's real heap is >= memoryLimit.

You might also be seeing some artifacts of v8's heap management. Perhaps once it's allocated a page of memory it keeps holding onto that memory for some time. I'm not sure, I haven't actually looked into this in detail.

**Comment by jeromegn** [comment]
Yes that makes sense.

The heap is still massive, even without the externally allocated array buffers. `getHeapStatistics()` reports over 200MB of heap after a single request which allocated a buffer (1.5MB), decoded to a string (~3MB), sent it back and forth a few times. Not nearly enough times to make it grow by that much.

In any case, I don't think it's isolated-vm's fault. I'm trying to find a way to profile this in a more granular manner.

**Comment by laverdet** [comment]
You were asking about support for native modules a while back. I implemented that last month though it remains undocumented. This could be a situation where a native module makes sense.

**Comment by jeromegn** [comment]
re stack traces: they've proven useful, but I can't use them in production since the latest isolated-vm won't compile on linux. I'm seeing the same errors I see on this repo's travis :)

re native module: I saw a commit about that, but I couldn't quite make out (yet) how to use them. A quick explanation might help, or a test case!

**Comment by laverdet** [comment]
Ah the compilations error and warning have been fixed.

I added an example of what you need to do to get native modules working under isolated-vm: https://github.com/laverdet/isolated-vm/tree/master/native-example

**Comment by jeromegn** [comment]
Oh that's interesting.

I was doing this and it was sort of working:

```c++
#include <v8.h>

extern "C" {
  void InitForContext(v8::Isolate* isolate, v8::Local<v8::Context> context, v8::Local<v8::Object> target) {
    printf("hello from native module!\n");
  }
}
```

```javascript
const ivm = require('isolated-vm')
module.exports = new ivm.NativeModule("./build/Release/hello.node")
```

Your way may be better though :)

**Comment by laverdet** [comment]
You were on the right track!
