### ISSUE TITLE
Question: Why is `--no-node-snapshot` required with Node.js 20?

### ISSUE THREAD

**Issue by mhassan1** [laverdet/isolated-vm#420]
I'm looking for clarification on the `--no-node-snapshot` requirement for Node.js 20:
1. Why is it required with Node.js 20? I think I've seen some explanations in other GitHub issues, but it would be good to have an "official" answer.
2. Is it always required with Node.js 20? I have gotten one report of one user running M1 Mac who can replicate a crash consistently, but we have been running automated tests in Debian for a few weeks with no crashes.
3. Is there any way to set it from runtime code? As far as I can tell, the answer is no.

Thank you!

**Comment by laverdet** [comment]
It's because of the shared heap feature in v8, which was adopted only recently. The idea is that multiple isolates can share certain read-only information amongst themselves. It causes the process to crash when multiple isolates within the same process use different snapshots, though. I believe it to be a bug in v8 but I don't have the time to troubleshoot an issue like this.
