### ISSUE TITLE
Question about maintenance mode

### ISSUE THREAD

**Issue by jrdavismaine** [laverdet/isolated-vm#462]
RE: project status, i.e. the `isolated-vm is currently in maintenance mode. ` , has the `isolated-vm` team decided on a end of life date?

Reposting status for quick refernence:
```
isolated-vm is currently in maintenance mode. New features are not actively being added but existing features and new versions of nodejs are supported as possible. There are some major architectural changes which need to be added to improve the stability and security of the project. I don't have as much spare time as I did when I started this project, so there is not currently any plan for these improvements.
```

**Comment by laverdet** [comment]
The team is just me. I haven't had as much time to dedicate to free software over the past couple of years, so that's the status. This problem is still one of interest to me so I hope to find the time eventually for major changes. That is, EOL is not on the horizon. Also in the case I die or whatever there are other tools you can migrate to, and the lessons you learn from isolated-vm will still carry over in that case. For example Cloudflare has [workerd](https://github.com/cloudflare/workerd) which is maybe not as easy to get started with but offers more or less the same security model.

**Comment by jrdavismaine** [comment]
Thank you for taking the time to answer my question.
