### ISSUE TITLE
Zero-Copy references between Isolates

### ISSUE THREAD

**Issue by mogill** [laverdet/isolated-vm#57]
I would like to use `isolate-vm`'s multi-threading capabilities to implement parallel sort and scan algorithms, but the copy-in/out requirements add time and space complexity on the order of number of threads.

Are inter-isolate references possible with caveats?  `isolated-vm` enforces reasonable caveats about parallel access to shared resources (i.e.: I/O), might it be possible to implement zero-copy inter-isolate references with caveats (i.e.: read-only, persistent data)?

**Comment by laverdet** [comment]
I don't think this will be possible with objects.. v8 can run a garbage collection at any time which is allowed to move object data physically in memory.

Would you be able to represent your algorithm in the context of SharedArrayBuffer? This is currently the only supported way to truly share data between isolates. So for instance a map reduce algorithm on a large buffer of floating points could be made parallel with SharedArrayBuffer + Float64Array.

**Comment by laverdet** [comment]
Your question inspired me to build a compelling example of a sort function which runs in parallel. You can check that out here [parallel-sort-example.js](https://github.com/laverdet/isolated-vm/blob/master/parallel-sort-example.js).

**Comment by mogill** [comment]
Thank you for your overly-generous response and example implementation -- and my apologies for not replying sooner.  Indeed, my interest in parallel JS has always failed to pay the bills and I'm only able to work on it in my spare time.  My question was not meant as an obligation to you in any way, I intended to keep this to a thought exercise.

Ideally, I want to implement a general extension of `Array.sort` which accepts a user-defined compare function and returns a permuted array.  The user-defined function dereferences the user's objects and there's no easy way to separate that operation from the comparison logic because they are in the same function.  Even if it were split into two passes, the library would need to first sequentially calculate and store all N^2 comparisons before entering the parallel sort.  Applications where the comparison function is expensive (i.e.: string distance) stand to benefit even when the list to be sorted is relatively short.

Regardless of `isolated-vm`'s suitability for sort, I'm impressed with it's "metaness", exposing the v8 runtime through a JS interface am sold on it's potential.  Keep up the good work!

**Comment by laverdet** [comment]
Depending on your use-case `Array.sort` may not be the best abstraction for your sort. Most standard libraries provide sorting functions that accept a predicate function, that is a function that compares two values and returns their relationship. `Array.sort()` wants you to return 0, positive, or negative.. in C++ `std::sort()` accepts just `operator<(T left, T right)`, for example. Library authors like this abstraction because it uses no extra memory to run, i.e. you can sort the array in place. This abstraction works well if comparing elements is cheap and you have a lot of elements to compare. In that case, the quicksort example I provided above is probably the best way to sort.

On the other hand if comparing elements is expensive it makes sense to use a scoring callback which generates a score for each element and then uses those scores as inputs to the predicate function to sort the original array. In that case you could use isolated-vm to parallelize the scoring callback and then perform the sort in the original thread using the results of the parallelized scoring callback, or you could parallelize both stages if you have both many elements and the comparison is expensive. That way you only have to hold N scores instead of N^2 comparisons. String distance would fall into this category.

**Comment by mogill** [comment]
Because it's also relevant here, I will note the issue of zero-copy shared-memory parallelism has come up on a thread about Node workers (https://github.com/nodejs/worker/issues/4#issuecomment-378414276) noting a few functions which would not have any expected speedup due to copy-in/out overhead.
