### ISSUE TITLE
Copying a 0 length buffer between isolates?

### ISSUE THREAD

**Issue by mrkurt** [laverdet/isolated-vm#69]
We're hitting this error trying to send an empty buffer to a different isolate: https://github.com/laverdet/isolated-vm/blob/44d3fd9551891889fdae689d9bbfe2845adc8198/src/external_copy.cc#L481

In this case, we need to be able to distinguish between `null` and empty. What's the best way to send a 0 length buffer between isolates?

**Comment by mrkurt** [comment]
Oh, it looks like it's only hitting that path when we specify `transferOut`. I think I got it. :D

**Comment by laverdet** [comment]
Yeah the problem is that when you transfer an ArrayBuffer out of an isolate it needs to be invalidated, but the way this manifests itself in JS is a value of 0 for `byteLength`. These transferred ArrayBuffers then become pretty much indistinguishable from 0-length ArrayBuffers. So by removing the check I open you up to a different class of error that could be difficult to track.
