### ISSUE TITLE
Any plan to support es6 modules?

### ISSUE THREAD

**Issue by idleman** [laverdet/isolated-vm#71]
Is there any plan to add support for es6 modules similar to node vm.Module class?

**Comment by laverdet** [comment]
If there's demand for it then sure. There's nothing that you can do with v8 modules that you can't do right now with a bit of babel so it doesn't seem super important to implement though.

**Comment by idleman** [comment]
I know, but using the "real" stuff may provide better debug information in case of errors and so on. However, I find your library super great and I am on my way to implement it through babel.

Would you appreciate pull requests that adds support for es modules? I may be able to pull something together in the coming week or so.

**Comment by idleman** [comment]
I have created a fork and started to do some work: https://github.com/idleman/isolated-vm/commit/7e9f8725482705f89536c3b6910e5e8365ac45e8

But I am unsure the "module_handle.cc" class should be implemented and what API I should expose to the user to make is as easy as possible for us. [v8::Module class](https://v8.paulfryzel.com/docs/master/classv8_1_1_module.html). Any suggestions?

**Comment by laverdet** [comment]
Ok I took some time to read up on v8's Module implementation, and nodejs's implementation as well. It seems nodejs diverges a little bit and introduces a separate "linking" stage which v8 doesn't actually have a concept of, and this isn't mentioned in ES6's module specification either. From what I can guess nodejs has this extra linking stage to make it easier for modules to resolve asynchronously. Since the `instantiate` stage must be synchronous they've added a separate stage which can run asynchronously.

In the case of isolated-vm this actually gets really hairy since there's more than one isolate so every operation is generally asynchronous by nature.

I think it's probably best to build something simple for now and then we could add fancy callback features later. Something like this:
```js
let isolate = new ivm.Isolate;
let context = isolate.createContextSync();

let modules = {};
async function loadModule(name) {
  if (name in modules) {
    return modules[name];
  }
  let src = fs.readFileSync(`${name}.js`); // or whatever
  let mod = await isolate.compileModule(src);
  // This corresponds to the same property in nodejs, and `GetModuleRequest()` in v8.
  // It would be a frozen array of strings
  let deps = mod.dependencySpecifiers;
  for (let dep of deps) {
    // This resolve function would store this reference in a C++ structure on the ModuleHandle 
    // instance. Nothing would actually happen in v8 during the call to `resolve`.
    mod.resolve(dep, loadModule(dep));
  }
  return modules[name] = mod;
}

let main = await loadModule('main');

// `instantiate` would refer to the information passed earlier to `resolve` calls. In the case a 
// dependency wasn't resolved then this would just throw an error
await main.instantiate(context);
// This should be the easiest part
await main.evaluate();
```

v8 and nodejs both want to use a callback for `instantiate` (or `link`) but I think avoiding that here will save us a lot of grief. The user would be required to iterate over a module's dependencies and "resolve" them before calling instantiate. That way the child isolate has everything it needs to instantiate a module ahead of time. It also doesn't back us into a corner here and if we're feeling brave we could add a callback argument to `instantiate` which would take the job of `resolve`.

I think first you'll need some kind of wrapper structure around v8::Module so you can keep track of the resolution information. This breaks the convention of isolated-vm a bit so I wanted to point it out. I think you'd need something like this:

```js
class IsolatedModule {
  RemoteHandle<v8::Module> module;
  std::mutex mutex; // You would need to hold this while reading/mutating `resolutions`
  std::vector<std::string> dependency_specifiers;
  std::unordered_map<std::string, std::shared_ptr<IsolatedModule>> resolutions;
};
```

**Comment by idleman** [comment]
Thanks for the help. I have created a pull request: [https://github.com/laverdet/isolated-vm/pull/72](https://github.com/laverdet/isolated-vm/pull/72). It is probably better to continue the discussion there so I am closing this issue now.
