### ISSUE TITLE
Buffer not available inside an isolate

### ISSUE THREAD

**Issue by lkoskela** [laverdet/isolated-vm#89]
I couldn't find a mention of this in the readme so I'm not sure if there's a reason why the `Buffer` class isn't available inside an isolate?

I suppose one could define a "local" implementation of `Buffer` inside the isolate that would proxy everything to the host where the work would be done with Node's built-in `Buffer` class. Is there a better way to make `Buffer` available to an isolate context?

**Comment by laverdet** [comment]
It's the same reason `require` isn't available in an isolate, because both `Buffer` and `require` are parts of nodejs and not standard JavaScript. You do have access to `ArrayBuffer` and all the other `ArrayView` implementations, though. Actually, nodejs's `Buffer` implementation is just a wrapper around `Uint8Array` since nodejs v4.x. Since JS adopted typed arrays there's very little need to directly use nodejs buffers.

**Comment by lkoskela** [comment]
Ah, I see. I'd totally missed that distinction. Thanks!
