### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by patriksimek** [laverdet/isolated-vm#96]
Hey @laverdet, first of all, thank for this great library and for fixing all my previous issues super fast. Can you please help me understand what's the problem here?

```javascript
const ivm = require('isolated-vm');
const isolate = new ivm.Isolate();
const context = isolate.createContextSync();
context.global.setSync('ivm', ivm);

const func = isolate.compileScriptSync('new ivm.Reference(function test(data) { return data.length; })').runSync(context);
let counter = 0;

for (let i = 0; i < 500; i++) {
	counter += func.applySync(null, [new ivm.ExternalCopy('x'.repeat(400000)).copyInto()]);
}

isolate.dispose();
```

This code runs pretty fast without any issue. With just a small modification (data to be passed to the isolate are wrapped to an object), the process breaks with the exception.

```javascript
const ivm = require('isolated-vm');
const isolate = new ivm.Isolate();
const context = isolate.createContextSync();
context.global.setSync('ivm', ivm);

const func = isolate.compileScriptSync('new ivm.Reference(function test(data) { return data.text.length; })').runSync(context);
let counter = 0;

for (let i = 0; i < 500; i++) {
	counter += func.applySync(null, [new ivm.ExternalCopy({ text: 'x'.repeat(400000) }).copyInto()]);
}

isolate.dispose();
```
Results in:
```
Error: Isolate was disposed during execution due to memory limit
```

Thank you!

**Comment by laverdet** [comment]
Ok I'll answer *why* this is happening first. When you create an isolate in v8 you get to set a memory limit, but when v8 hits that memory limit and execution of JS can no longer continue it handles that error by crashing the entire process. So what isolated-vm does is it gives v8 a higher memory limit, and then listens to garbage collection events for any signs of trouble. If isolated-vm detects a garbage collection event and the memory limit is approaching the maximum it terminates the isolate immediately to avoid any risk of the process crashing. It's unfortunately pretty heuristic-driven so it leads to weird cases like you observed here.

This situation actually got a lot better in node v10.x-- v8 lets you subscribe to a "near heap limit" notification right before the process is about to crash. It also gives you the ability to temporarily raise the heap limit to whatever you want. So in node v10 when it's about to hit the heap limit it gives v8 some extra memory and then requests that the isolate terminates as soon as possible which means the old method of looking for garbage collection events probably doesn't need to be as aggressive.

I took a look at your example and the event that causes the isolate to dispose in the second example is just an "incremental marking" garbage collection event, which apparently means no garbage has actually been collected. I think I can safely ignore these events because a "real" garbage collection is always quick to follow. Ignoring the event fixes this specific case and doesn't cause any of my tests to fail so I think it's probably safe to do that. Please let me know if the changes to master fixes the issue you were running into.

**Comment by patriksimek** [comment]
Just tested the latest changes and it is stable now. Thank you for the fix and the explanation.
